CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA parking;

CREATE TYPE parking.parking_session_status AS ENUM (
    'open',
    'paid',
    'voided'
);

CREATE SEQUENCE parking.ticket_number_seq
    AS bigint
    START WITH 1000
    INCREMENT BY 1
    MINVALUE 1000
    MAXVALUE 9223372036854775807
    CACHE 1
    NO CYCLE;

CREATE TABLE parking.lots (
    lot_id integer GENERATED BY DEFAULT AS IDENTITY,
    lot_code text NOT NULL,
    lot_name text NOT NULL,
    capacity integer NOT NULL,
    opened_on date NOT NULL,
    CONSTRAINT lots_pk PRIMARY KEY (lot_id),
    CONSTRAINT lots_code_uk UNIQUE (lot_code),
    CONSTRAINT lots_capacity_check CHECK (capacity > 0)
);

CREATE TABLE parking.vehicles (
    vehicle_id uuid DEFAULT gen_random_uuid() NOT NULL,
    license_plate text NOT NULL,
    state_code text NOT NULL,
    vehicle_class text NOT NULL,
    CONSTRAINT vehicles_pk PRIMARY KEY (vehicle_id),
    CONSTRAINT vehicles_plate_uk UNIQUE (license_plate, state_code),
    CONSTRAINT vehicles_class_check CHECK (vehicle_class IN ('compact', 'standard', 'oversize'))
);

CREATE TABLE parking.parking_sessions (
    parking_session_id bigint DEFAULT nextval('parking.ticket_number_seq'::regclass) NOT NULL,
    lot_id integer NOT NULL,
    vehicle_id uuid NOT NULL,
    status parking.parking_session_status NOT NULL DEFAULT 'open',
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    amount_due numeric(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT parking_sessions_pk PRIMARY KEY (parking_session_id),
    CONSTRAINT parking_sessions_lot_fk FOREIGN KEY (lot_id) REFERENCES parking.lots(lot_id),
    CONSTRAINT parking_sessions_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES parking.vehicles(vehicle_id),
    CONSTRAINT parking_sessions_amount_check CHECK (amount_due >= 0),
    CONSTRAINT parking_sessions_time_check CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX parking_sessions_status_idx
    ON parking.parking_sessions USING btree (status);

CREATE INDEX parking_sessions_started_at_idx
    ON parking.parking_sessions USING btree (started_at);

CREATE INDEX vehicles_license_plate_idx
    ON parking.vehicles USING btree (license_plate);

CREATE VIEW parking.open_parking_sessions AS
 SELECT parking_sessions.parking_session_id,
    lots.lot_code,
    vehicles.license_plate,
    vehicles.state_code,
    parking_sessions.started_at,
    parking_sessions.amount_due
   FROM parking.parking_sessions
     JOIN parking.lots ON lots.lot_id = parking_sessions.lot_id
     JOIN parking.vehicles ON vehicles.vehicle_id = parking_sessions.vehicle_id
  WHERE parking_sessions.status = 'open';
