-- DbState PostgreSQL Slice 2 fixture.
-- Test-only. Apply only to a disposable local PostgreSQL database.
-- Do not use against production, UAT, staging, or shared databases.

DROP SCHEMA IF EXISTS dbstate_slice2 CASCADE;
CREATE SCHEMA dbstate_slice2;

CREATE TABLE dbstate_slice2.sample_accounts (
    account_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code text NOT NULL DEFAULT 'sample',
    display_name text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dbstate_slice2.sample_events (
    event_id integer NOT NULL,
    account_id integer,
    event_name text NOT NULL,
    notes text
);

GRANT USAGE ON SCHEMA dbstate_slice2 TO PUBLIC;
GRANT SELECT ON TABLE dbstate_slice2.sample_accounts TO PUBLIC;
